server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: blog-service
  redis:
    host: 127.0.0.1 # Redis服务器地址，这里假设是本地，如果是远程服务器则填写对应的IP地址
    port: 6379 # Redis服务器端口，默认是6379
    password:  # Redis密码，如果没有设置密码则留空即可
    database: 0 # 使用的Redis数据库编号，默认是0，可以根据需要选择0-15之间的数据库编号
    erializer:
      key: org.springframework.data.redis.serializer.StringRedisSerializer
      value: org.springframework.data.redis.serializer.GenericJackson2JsonRedisSerializer
    # 文件上传配置
  servlet:

    multipart:
    max-file-size: 10MB
    max-request-size: 10MB

  # 二维码配置

qrcode:
  # Windows系统示例
  save-path: D:/blog/upload/qrcode/
  # Linux系统示例
  # save-path: /usr/local/blog/upload/qrcode/
  # 开发环境示例
  access-path: http://localhost:8081/api/qrcode/


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 15

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
  # 设置为true开启自动续期
  is - auto - renew: true

logging:
  level:
    cn.dev33.satoken: DEBUG

# 微信支付配置

wx:
  pay:
    # APIv3密钥
    api-v3-key:
    # APPID
    appid:
    # 商户ID
    mch-id:
    # 商户API证书序列号
    mch-serial-no:
    # 接收支付结果通知地址
    notify-domain: https://127.0.0.1/pay/wxNativeNotify
    # 退款回调通知
    refund-notify-domain: https://127.0.0.1/pay/wxRefundNotify
    # 商户私钥文件路径
    private-key-path: D:\key\apiclient_key.pem
